stackname: kathautsavmodule
env_folder: env_vars
replicas:
  dev: 1
  prod: 10
restart_policy: any
max_mem: 1024M
max_cpu: 1
traefik_application_port: 3200
traefik_https_enable: true
traefik_ssl_provider: letsencrypt