// Valid Input Fields
export const VALID_INITIATE = 'VALID_INITIATE';
export const VALID_SUCCESS = 'VALID_SUCCESS';
export const VALID_FAIL = 'VALID_FAIL';
export const IS_SHOW_POPUP = 'IS_SHOW_POPUP'

//Validate School Step One Registration
export const VALID_INITIATE_SCHOOL_STEPONE = 'VALID_INITIATE_SCHOOL_STEPONE';
export const VALID_SUCCESS_SCHOOL_STEPONE = 'VALID_SUCCESS_SCHOOL_STEPONE';
export const VALID_FAIL_SCHOOL_STEPONE = 'VALID_FAIL_SCHOOL_STEPONE';
export const IS_SHOW_POPUP_SCHOOL = 'IS_SHOW_POPUP_SCHOOL';
export const VALID_SUCCESS_SCHOOL_STEPTWO = 'VALID_SUCCESS_SCHOOL_STEPTWO';
export const VALID_FAIL_SCHOOL_STEPTWO = 'VALID_FAIL_SCHOOL_STEPTWO';
export const VALID_INITIATE_SCHOOL_STEPTWO = 'VALID_INITIATE_SCHOOL_STEPTWO';
export const UPDATE_STEP = 'UPDATE_STEP';

// Contact Page
export const Upload_Data_Initiate ='Upload_Data_Initiate'

// Registration Response
export const SHOW_RESPONSE_POPUP = 'SHOW_RESPONSE_POPUP';
export const SET_REGISTRATION_DATA = 'SET_REGISTRATION_DATA';

//Registration loader

export const SHOW_LOADER = 'SHOW_LOADER';
export const IS_UPLOAD_SUCCESS='IS_UPLOAD_SUCCESS';
export const SHOW_SNACK_BAR='SHOW_SNACK_BAR';
